# Generated by Django 3.1.4 on 2020-12-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CNIC',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
