# Generated by Django 3.1.2 on 2020-12-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('reg_no', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.PositiveIntegerField()),
                ('body_type', models.CharField(choices=[('SDN', 'SEDAN'), ('CPE', 'COUPE'), ('STW', 'STATION WAGON'), ('HTB', 'HATCHBACK'), ('CNV', 'CONVERTABLE')], max_length=100)),
                ('engine_capacity', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('transmission', models.CharField(choices=[('MAN', 'MANUAL'), ('AUT', 'AUTOMATIC')], max_length=100)),
                ('fuel', models.CharField(choices=[('PET', 'PETROL'), ('DSL', 'DIESEL')], max_length=100)),
                ('image', models.ImageField(default='default_car.png', upload_to='car_pics')),
                ('accident_details', models.TextField(blank=True, default='')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DRIVER',
            fields=[
                ('CNIC', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('hourly_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
