# Generated by Django 3.1.4 on 2020-12-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREDIT_CARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default='', max_length=25)),
                ('code', models.CharField(default='', max_length=4)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.credit_card'),
        ),
    ]
