# Generated by Django 3.1.2 on 2020-12-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_car.jpg', upload_to='car_pics'),
        ),
    ]
