# Generated by Django 3.1.4 on 2020-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='damages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='latefine',
            name='per_day_fine',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='DAMAGES',
        ),
    ]
