# Generated by Django 3.1.2 on 2020-12-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
