# Generated by Django 3.1.2 on 2020-12-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('pickup_location', models.TextField(blank=True, default='')),
                ('is_driver_needed', models.BooleanField()),
                ('selected_car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agency.car')),
            ],
        ),
    ]
