# Generated by Django 3.1.2 on 2020-12-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20201226_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.fare'),
        ),
    ]
