# Generated by Django 3.1.2 on 2020-12-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.car'),
        ),
    ]
