# Generated by Django 3.1.2 on 2020-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_car.png', upload_to='car_pics'),
        ),
    ]
