# Generated by Django 3.1.4 on 2020-12-26 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20201227_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.payment'),
        ),
    ]
