# Generated by Django 3.1.2 on 2020-12-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201222_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_car',
        ),
    ]
