# Generated by Django 3.1.2 on 2020-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201212_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='CNIC',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
    ]
