# Generated by Django 3.1.2 on 2020-12-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_booking_selected_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_car',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
    ]
