# Generated by Django 3.1.4 on 2020-12-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20201223_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='allocated_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.driver'),
        ),
    ]
