# Generated by Django 3.1.4 on 2020-12-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20201223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
