# Generated by Django 3.1.2 on 2020-12-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_driver_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='allocated_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='allocated_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.driver'),
        ),
    ]
