# Generated by Django 3.1.4 on 2020-12-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_booking_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RENTAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateTimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agency.booking')),
            ],
        ),
    ]
