# Generated by Django 3.1.2 on 2020-12-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_fare',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('ECO', 'ECONOMY'), ('BIZ', 'BUSINESS'), ('LUX', 'LUXURY')], default='ECONOMY', max_length=100),
        ),
    ]
