# Generated by Django 3.1.2 on 2020-12-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20201225_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FARE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('ECO', 'ECONOMY'), ('BIZ', 'BUSINESS'), ('LUX', 'LUXURY')], max_length=100)),
                ('car_fare', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_fare',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
        migrations.AddField(
            model_name='car',
            name='fare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.fare'),
        ),
    ]
