# Generated by Django 3.1.4 on 2020-12-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20201225_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='agency.booking'),
        ),
    ]
